package cmd
package cmd

import (
	"context"
	"fmt"


















































































}	return nil	fmt.Println("✅ All tests passed!")	}		return fmt.Errorf("❌ Tests failed:\n%s", friendlyError)		friendlyError := translator.Translate(err.Error())		translator := bazel.NewErrorTranslator()		// Translate Bazel error to user-friendly message	if err := executor.Test(ctx, targets); err != nil {	// Execute tests	}		fmt.Printf("🧪 Testing: %s\n", strings.Join(serviceNames, ", "))	} else {		fmt.Println("🧪 Running all tests...")	if len(serviceNames) == 0 {	serviceNames := extractServiceNames(args)	// Show user-friendly message	}		targets = append(targets, "//...")		// Test everything	} else {		targets = append(targets, serviceToTarget(testService))		// Test from --service flag	} else if testService != "" {		}			targets = append(targets, serviceToTarget(service))		for _, service := range args {		// Test specific services	if len(args) > 0 {		var targets []string	// Determine what to test	}		return err	if err != nil {	executor, err := bazel.NewExecutor(workspaceRoot, testVerbose)	// Create Bazel executor	}		return fmt.Errorf("not in a forge workspace: %w", err)	if err != nil {	workspaceRoot, err := findWorkspaceRoot()	// Get workspace root	ctx := context.Background()func runTest(cmd *cobra.Command, args []string) error {}	testCmd.Flags().BoolVar(&testCI, "ci", false, "Run in CI mode (no cache, fail fast)")	testCmd.Flags().StringVarP(&testService, "service", "s", "", "Test specific service")	testCmd.Flags().BoolVarP(&testVerbose, "verbose", "v", false, "Show detailed test output")	rootCmd.AddCommand(testCmd)func init() {}	RunE: runTest,  forge test --ci             # Run in CI mode (no cache, fail fast)`,  forge test --verbose        # Show detailed test output  forge test api-server       # Test specific service  forge test                  # Run all testsExamples:	Long: `Run tests for one or more services.	Short: "Run tests",	Use:   "test [service...]",var testCmd = &cobra.Command{)	testCI      bool	testService string	testVerbose boolvar ()	"github.com/spf13/cobra"	"github.com/dosanma1/forge-cli/internal/bazel"	"strings"